---
workflow:
    rules:
      - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
        when: never
      - when: always

variables:
  TF_DIR: ${CI_PROJECT_DIR}
  TF_STATE_NAME: "eks-tf"
  ADDRESS: "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/terraform/state/${STATE_NAME}"

stages:
  - validate
  - plan
  - apply
  - destroy

image:
  name: hashicorp/terraform:light
  entrypoint: [""]

before_script:
  - terraform --version
  - export GITLAB_ACCESS_TOKEN=input TF_STATE_NAME=eks-tf 
  - terraform init -reconfigure -backend-config="address=https://gitlab.com/api/v4/projects/55484482/terraform/state/$TF_STATE_NAME" -backend-config="lock_address=https://gitlab.com/api/v4/projects/55484482/terraform/state/$TF_STATE_NAME/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/55484482/terraform/state/$TF_STATE_NAME/lock" -backend-config="username=Iam-Manishkumar" -backend-config="password=$GITLAB_ACCESS_TOKEN" -backend-config="lock_method=POST"  -backend-config="unlock_method=DELETE" -backend-config="retry_wait_min=5"
validate:
  stage: validate
  script:
    - terraform validate


plan:
  stage: plan
  script:
    - export GITLAB_ACCESS_TOKEN=$TOKEN
    - terraform plan 
  dependencies:
    - validate


apply:
  stage: apply
  script:
    - terraform apply  -auto-approve
  dependencies:
    - plan
  allow_failure: true

destroy:
  stage: destroy
  script:
    - terraform destroy  -auto-approve
  allow_failure: true  

  when: always